### ISSUE TITLE
Change @Table annotation name

### ISSUE THREAD

**Issue by codebymikey** [kobakei/spot#1]
This is a pretty neat idea, just a thought as it threw me for a loop at first regarding its purpose.

Do you mind changing the `@Table` annotation name to something a bit more appropriate like `@SharedPref` or `@Pref` to avoid any further confusion?

Tables are usually associated with databases, and from what I can tell, this is SharedPreference specific.

**Comment by kobakei** [comment]
Renamed at 0.1.1
